### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by payphonePYF** [KingJamesSong/PDETraversal#1]
Hello, thank you very much for your work, where can I get the checkpoint.pt?

**Comment by KingJamesSong** [comment]
Hi, Thanks for your interest in our work!

Since our work relies on pre-trained VAEs/GANS, it is easy to train the model and get the results. 

For example, to get the results on AnimeFace with SNGAN, You need to run anime.sh to first train the model.

Feel free to ask any further questions.

**Comment by payphonePYF** [comment]
Thank you for your timely response which has helped me solve the problem
